### ISSUE TITLE
Tinlake Pool ConsolFreight Series 4 - False display of TIN-token's current price

### ISSUE THREAD

**Issue by Tjure07** [centrifuge/tinlake-pools-mainnet#15]
Hi guys,

I noticed this error a few times before: in the investment pool of ConsolFreight 4 on Tinlake the current price of the TIN-token is erroneous from time to time. Attached is the snapshot from the 3rd of December. 

Although this token-price would be nice to have, this is a bit misleading from an investor's point of view.

Thanks for looking into it.

Best regards,
Christian

![Tinlake CF4 TIN-token display current price](https://user-images.githubusercontent.com/46523585/100996355-40c5d300-3559-11eb-9f2e-ce5cd42c8283.PNG)

**Comment by denniswell** [comment]
Thanks for pointing this out @tjure07. We looked into it and will tackle it soon.
